// Alias editoriales explícitos del corpus. Compartido con el cliente, sin dependencias de servidor.
const NOMBRES: Record<string, string> = {
  TVN: "TVN",
  "tvn-2.com": "TVN",
  "critica.com.pa": "Crítica",
  "prensa.com": "La Prensa",
  "panamaamerica.com.pa": "Panamá América",
  "laestrella.com.pa": "La Estrella de Panamá",
  "diaadia.com.pa": "Día a Día",
  "midiario.com": "Mi Diario",
  "telemetro.com": "Telemetro",
  "rpctv.com": "RPC",
  "asamblea.gob.pa": "Asamblea Nacional",
  "mire.gob.pa": "Ministerio de Relaciones Exteriores",
  "efe.com": "EFE",
  "prensa-latina.cu": "Prensa Latina",
  "europapress.es": "Europa Press",
  "cnnespanol.cnn.com": "CNN en Español",
  "cnnchile.com": "CNN Chile",
  "dw.com": "DW",
  "actualidad-rt.com": "RT",
  "infobae.com": "Infobae",
  "elpais.com": "El País",
  "elmundo.es": "El Mundo",
  "abc.es": "ABC",
  "clarin.com": "Clarín",
  "lanacion.com.ar": "La Nación",
  "nacion.com": "La Nación",
  "teletica.com": "Teletica",
  "prensalibre.com": "Prensa Libre",
  "eltiempo.com": "El Tiempo",
  "elespectador.com": "El Espectador",
  "elcolombiano.com": "El Colombiano",
  "semana.com": "Semana",
  "elcomercio.pe": "El Comercio",
  "larepublica.pe": "La República",
  "eluniversal.com.mx": "El Universal",
  "listindiario.com": "Listín Diario",
  "diariolibre.com": "Diario Libre",
  "biobiochile.cl": "BioBioChile",
  "latercera.com": "La Tercera",
  "rtve.es": "RTVE",
  "telemundo.com": "Telemundo",
};

export function nombreMedio(medio: string): string {
  return Object.hasOwn(NOMBRES, medio) ? NOMBRES[medio] : medio;
}
